filebeat.inputs:
- type: log
  include_lines: ['^[0-9]{4}\-[0-9]{2}\-[0-9]{2}']
  exclude_lines: ['isSoaServerReady']
  tags: ["weblogic-access-log"]
  paths:
    # Instalação local do Filebeat
    # - logs/access.log
    # Docker
    - /fakelogs/access.log

- type: log
  include_lines: ['^\[[0-9]{4}\-[0-9]{2}\-[0-9]{2}']
  exclude_lines: ['\[NOTIFICATION\]']
  tags: ["weblogic-diagnostic-log"]
  paths:
    # Instalação local do Filebeat
    # - logs/diagnostic.log
    # Docker
    - /fakelogs/diagnostic.log

- type: log
  include_lines: ['^####']
  exclude_lines: ['<Info>']
  tags: ["weblogic-server-log"]
  paths:
    # Instalação local do Filebeat
    # - logs/server.log
    # Docker
    - /fakelogs/server.log

- type: log
  include_lines: ['^<[0-9]{2}']
  exclude_lines: [' INFO ']
  tags: ["weblogic-stdout-log"]
  paths:
    # Instalação local do Filebeat
    # - logs/stdout.txt
    # Docker
    - /fakelogs/stdout.txt

- type: log
  include_lines: ['^[0-9]{4}\-[0-9]{2}\-[0-9]{2}']
  tags: ["weblogic-gc-log"]
  paths:
    # Instalação local do Filebeat
    # - logs/gc.log
    # Docker
    - /fakelogs/gc.log

output.logstash:
  # Porta que o Filebeat envia para o Logstash escutar
  hosts: ["logstash:5043"]